In [1]:
import cv2
import time

In [16]:
def generate_dataset(Name):
    face_classifier = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
    
    def face_cropped(img):
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = face_classifier.detectMultiScale(gray, 1.3, 5)
        
        if len(faces) == 0:
            return None
        for (x, y, w, h) in faces:
            cropped_face = img[y:y+h, x:x+w]
        return cropped_face
    
    cap = cv2.VideoCapture(1)
    if not cap.isOpened():
        print("Error: Could not open video capture")
        return
    
    img_id = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            print("Failed to capture image")
            break
        
        cropped_face = face_cropped(frame)
        if cropped_face is not None:
            img_id += 1
            face = cv2.resize(cropped_face, (200, 200))
            face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)
            file_name_path = "C:/Vaibhav Data/Proffesional/Engineering/NHCE/Sem 6/Mini Project - III/Face_recog/data/"+ Name + str(img_id) + ".jpg"
            cv2.imwrite(file_name_path, face)
            cv2.putText(face, str(img_id), (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)
            
            cv2.imshow("Cropped_Face", face)
            if cv2.waitKey(1) == 13 or img_id == 250:
                break
        else:
            cv2.imshow("Camera Feed", frame)
            if cv2.waitKey(1) == 13:
                break
    
    cap.release()
    cv2.destroyAllWindows()
    print("Collecting samples is completed.")

# generate_dataset("Vaibhav")
# time.sleep(10)
# generate_dataset("Sruthi")
# time.sleep(10)
generate_dataset("Kamran")
time.sleep(10)
generate_dataset("Karthik")

In [2]:
import numpy as np

In [3]:
import os

def find_images(directory, extensions=None):
    """
    Finds all images in a given directory with specified extensions.
    
    Args:
        directory (str): Path to the directory to search for images.
        extensions (list): List of valid image file extensions (default: common formats).
    
    Returns:
        list: List of paths to image files.
    """
    if extensions is None:
        # Default to common image extensions
        extensions = ['.jpg', '.jpeg', '.png']
    
    # Normalize extensions to lowercase
    extensions = [ext.lower() for ext in extensions]
    
    # List to hold image paths
    image_files = []
    
    # Walk through the directory
    for root, _, files in os.walk(directory):
        for file in files:
            if os.path.splitext(file)[1].lower() in extensions:
                image_files.append(os.path.join(root, file))
    
    return image_files

# Example usage
directory_path = "indian_faces"  # Replace with your directory path
images = find_images(directory_path)

print("Found Images:")
count = 0
for image in images:
    count += 1
    print(count, image)



Found Images:
1 indian_faces\001.jpg
2 indian_faces\002.jpg
3 indian_faces\003.jpg
4 indian_faces\004.jpg
5 indian_faces\005.jpg
6 indian_faces\006.jpg
7 indian_faces\007.jpg
8 indian_faces\008.jpg
9 indian_faces\009.jpg
10 indian_faces\010.jpg
11 indian_faces\011.jpg
12 indian_faces\012.jpg
13 indian_faces\013.jpg
14 indian_faces\014.jpg
15 indian_faces\015.jpg
16 indian_faces\016.jpg
17 indian_faces\017.jpg
18 indian_faces\018.jpg
19 indian_faces\019.jpg
20 indian_faces\020.jpg
21 indian_faces\021.jpg
22 indian_faces\022.jpg
23 indian_faces\023.jpg
24 indian_faces\024.jpg
25 indian_faces\025.jpg
26 indian_faces\026.jpg
27 indian_faces\027.jpg
28 indian_faces\028.jpg
29 indian_faces\029.jpg
30 indian_faces\030.jpg
31 indian_faces\031.jpg
32 indian_faces\032.jpg
33 indian_faces\033.jpg
34 indian_faces\034.jpg
35 indian_faces\035.jpg
36 indian_faces\036.jpg
37 indian_faces\037.jpg
38 indian_faces\038.jpg
39 indian_faces\039.jpg
40 indian_faces\040.jpg
41 indian_faces\041.jpg
42 indian_f

In [4]:
import cv2
import os

def extract_faces(image_path, output_dir, count,resize_dim=(200, 200)):
    """
    Extracts faces from an image, converts them to grayscale, resizes them, 
    and saves them as 50x50 images.
    
    Args:
        image_path (str): Path to the input image.
        output_dir (str): Directory to save the extracted face images.
        resize_dim (tuple): Dimensions to resize the face images (default: (50, 50)).
    """
    # Load the image
    image = cv2.imread(image_path)
    if image is None:
        print(f"Error: Unable to load image {image_path}")
        return
    
    # Convert to grayscale for face detection
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    # Load pre-trained Haar Cascade for face detection
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    
    # Detect faces in the image
    faces = face_cascade.detectMultiScale(gray_image, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))
    
    if len(faces) == 0:
        print("No faces detected in the image.")
        return
    
    # Ensure the output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    # Process each detected face
    for i, (x, y, w, h) in enumerate(faces):
        # Extract the face region
        face = gray_image[y:y+h, x:x+w]
        
        # Resize to the desired dimensions
        resized_face = cv2.resize(face, resize_dim)
        
        # Save the resized grayscale face image
        output_path = os.path.join(output_dir, f"intruder_{count+i+1}.png")
        cv2.imwrite(output_path, resized_face)
        print(f"Saved face {i+1} to {output_path}")

directory_path = "indian_faces"  # Replace with your directory path
images = find_images(directory_path)

print("Found Images:")
for idx, image in enumerate(images):
    extract_faces(image, "data", count=idx+1)

Found Images:
Saved face 1 to data\intruder_2.png
Saved face 1 to data\intruder_3.png
Saved face 1 to data\intruder_4.png
Saved face 1 to data\intruder_5.png
Saved face 1 to data\intruder_6.png
Saved face 1 to data\intruder_7.png
Saved face 1 to data\intruder_8.png
Saved face 1 to data\intruder_9.png
Saved face 1 to data\intruder_10.png
Saved face 1 to data\intruder_11.png
Saved face 1 to data\intruder_12.png
Saved face 1 to data\intruder_13.png
Saved face 1 to data\intruder_14.png
Saved face 1 to data\intruder_15.png
Saved face 1 to data\intruder_16.png
Saved face 1 to data\intruder_17.png
Saved face 1 to data\intruder_18.png
Saved face 1 to data\intruder_19.png
Saved face 1 to data\intruder_20.png
Saved face 1 to data\intruder_21.png
Saved face 1 to data\intruder_22.png
Saved face 1 to data\intruder_23.png
Saved face 1 to data\intruder_24.png
Saved face 1 to data\intruder_25.png
Saved face 1 to data\intruder_26.png
Saved face 1 to data\intruder_27.png
Saved face 1 to data\intruder_28

In [6]:
# def my_label(image_name):
#     name = image_name.split('.')[0] 
    
#     if name=="Vaibhav":
#         return np.array([1,0])
#     elif name=="Sruthi":
#         return np.array([0,1])

def my_label(image_name):
    name = image_name.split('.')[0]  # Extract the part before the file extension
    
    if name.startswith("Vaibhav"):
        return np.array([1, 0, 0, 0, 0])
    elif name.startswith("Sruthi"):
        return np.array([0, 1, 0, 0, 0])
    elif name.startswith("Kamran"):
        return np.array([0, 0, 1, 0, 0])
    elif name.startswith("Karthik"):
        return np.array([0, 0, 0, 1, 0])
    else:
        return np.array([0, 0, 0, 0, 1])


In [7]:
import os
from random import shuffle
from tqdm import tqdm

In [8]:
def my_data():
    data = []
    for img in tqdm(os.listdir("data")):
        path=os.path.join("data",img)
        img_data = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img_data = cv2.resize(img_data, (50,50))
        data.append([np.array(img_data), my_label(img)])
        print(img)
    shuffle(data)  
    return data


In [9]:
data = my_data()
print(data)

  3%|▎         | 34/1250 [00:00<00:07, 164.38it/s]

intruder_10.png
intruder_100.png
intruder_101.png
intruder_102.png
intruder_103.png
intruder_104.png
intruder_105.png
intruder_106.png
intruder_107.png
intruder_108.png
intruder_109.png
intruder_11.png
intruder_110.png
intruder_111.png
intruder_112.png
intruder_113.png
intruder_114.png
intruder_115.png
intruder_116.png
intruder_117.png
intruder_118.png
intruder_119.png
intruder_12.png
intruder_120.png
intruder_121.png
intruder_122.png
intruder_123.png
intruder_124.png
intruder_125.png
intruder_126.png
intruder_127.png
intruder_128.png
intruder_129.png
intruder_13.png


  5%|▌         | 68/1250 [00:00<00:07, 167.57it/s]

intruder_130.png
intruder_131.png
intruder_132.png
intruder_133.png
intruder_134.png
intruder_135.png
intruder_136.png
intruder_137.png
intruder_138.png
intruder_139.png
intruder_14.png
intruder_140.png
intruder_141.png
intruder_142.png
intruder_143.png
intruder_144.png
intruder_145.png
intruder_146.png
intruder_147.png
intruder_148.png
intruder_149.png
intruder_15.png
intruder_150.png
intruder_151.png
intruder_152.png
intruder_153.png
intruder_154.png
intruder_155.png
intruder_156.png
intruder_157.png
intruder_158.png
intruder_159.png
intruder_16.png
intruder_160.png


  7%|▋         | 85/1250 [00:00<00:07, 162.53it/s]

intruder_161.png
intruder_162.png
intruder_163.png
intruder_164.png
intruder_165.png
intruder_166.png
intruder_167.png
intruder_168.png
intruder_169.png
intruder_17.png
intruder_170.png
intruder_171.png
intruder_172.png
intruder_173.png
intruder_174.png
intruder_175.png
intruder_176.png
intruder_177.png
intruder_178.png
intruder_179.png
intruder_18.png
intruder_180.png
intruder_181.png
intruder_182.png
intruder_183.png
intruder_184.png
intruder_185.png
intruder_186.png
intruder_187.png
intruder_188.png
intruder_189.png
intruder_19.png
intruder_190.png


 10%|▉         | 120/1250 [00:00<00:06, 166.15it/s]

intruder_191.png
intruder_192.png
intruder_193.png
intruder_194.png
intruder_195.png
intruder_196.png
intruder_197.png
intruder_198.png
intruder_199.png
intruder_2.png
intruder_20.png
intruder_200.png
intruder_201.png
intruder_202.png
intruder_203.png
intruder_204.png
intruder_205.png
intruder_206.png
intruder_207.png
intruder_208.png
intruder_209.png
intruder_21.png
intruder_210.png
intruder_211.png
intruder_212.png
intruder_213.png
intruder_214.png
intruder_215.png
intruder_216.png
intruder_217.png
intruder_218.png
intruder_219.png
intruder_22.png
intruder_220.png
intruder_221.png
intruder_222.png


 14%|█▍        | 173/1250 [00:01<00:06, 171.62it/s]

intruder_223.png
intruder_224.png
intruder_225.png
intruder_226.png
intruder_227.png
intruder_228.png
intruder_229.png
intruder_23.png
intruder_230.png
intruder_231.png
intruder_232.png
intruder_233.png
intruder_234.png
intruder_235.png
intruder_236.png
intruder_237.png
intruder_238.png
intruder_239.png
intruder_24.png
intruder_240.png
intruder_241.png
intruder_242.png
intruder_243.png
intruder_244.png
intruder_245.png
intruder_246.png
intruder_247.png
intruder_248.png
intruder_249.png
intruder_25.png
intruder_250.png
intruder_251.png
intruder_26.png
intruder_27.png
intruder_28.png
intruder_29.png


 15%|█▌        | 191/1250 [00:01<00:06, 169.22it/s]

intruder_3.png
intruder_30.png
intruder_31.png
intruder_32.png
intruder_33.png
intruder_34.png
intruder_35.png
intruder_36.png
intruder_37.png
intruder_38.png
intruder_39.png
intruder_4.png
intruder_40.png
intruder_41.png
intruder_42.png
intruder_43.png
intruder_44.png
intruder_45.png
intruder_46.png
intruder_47.png
intruder_48.png
intruder_49.png
intruder_5.png
intruder_50.png
intruder_51.png
intruder_52.png
intruder_53.png
intruder_54.png


 18%|█▊        | 224/1250 [00:01<00:07, 145.95it/s]

intruder_55.png
intruder_56.png
intruder_57.png
intruder_58.png
intruder_59.png
intruder_6.png
intruder_60.png
intruder_61.png
intruder_62.png
intruder_63.png
intruder_64.png
intruder_65.png
intruder_66.png
intruder_67.png
intruder_68.png
intruder_69.png
intruder_7.png
intruder_70.png
intruder_71.png
intruder_72.png
intruder_73.png
intruder_74.png
intruder_75.png
intruder_76.png
intruder_77.png
intruder_78.png
intruder_79.png


 22%|██▏       | 279/1250 [00:01<00:04, 212.85it/s]

intruder_8.png
intruder_80.png
intruder_81.png
intruder_82.png
intruder_83.png
intruder_84.png
intruder_85.png
intruder_86.png
intruder_87.png
intruder_88.png
intruder_89.png
intruder_9.png
intruder_90.png
intruder_91.png
intruder_92.png
intruder_93.png
intruder_94.png
intruder_95.png
intruder_96.png
intruder_97.png
intruder_98.png
intruder_99.png
Kamran1.jpg
Kamran10.jpg
Kamran100.jpg
Kamran101.jpg
Kamran102.jpg
Kamran103.jpg
Kamran104.jpg
Kamran105.jpg
Kamran106.jpg
Kamran107.jpg
Kamran108.jpg
Kamran109.jpg
Kamran11.jpg
Kamran110.jpg
Kamran111.jpg
Kamran112.jpg
Kamran113.jpg
Kamran114.jpg
Kamran115.jpg
Kamran116.jpg
Kamran117.jpg
Kamran118.jpg
Kamran119.jpg
Kamran12.jpg
Kamran120.jpg
Kamran121.jpg
Kamran122.jpg
Kamran123.jpg
Kamran124.jpg
Kamran125.jpg
Kamran126.jpg
Kamran127.jpg
Kamran128.jpg
Kamran129.jpg
Kamran13.jpg
Kamran130.jpg
Kamran131.jpg
Kamran132.jpg
Kamran133.jpg
Kamran134.jpg
Kamran135.jpg
Kamran136.jpg
Kamran137.jpg
Kamran138.jpg
Kamran139.jpg
Kamran14.jpg
Kamran140.jpg

 45%|████▌     | 566/1250 [00:01<00:00, 818.17it/s]

Kamran159.jpg
Kamran16.jpg
Kamran160.jpg
Kamran161.jpg
Kamran162.jpg
Kamran163.jpg
Kamran164.jpg
Kamran165.jpg
Kamran166.jpg
Kamran167.jpg
Kamran168.jpg
Kamran169.jpg
Kamran17.jpg
Kamran170.jpg
Kamran171.jpg
Kamran172.jpg
Kamran173.jpg
Kamran174.jpg
Kamran175.jpg
Kamran176.jpg
Kamran177.jpg
Kamran178.jpg
Kamran179.jpg
Kamran18.jpg
Kamran180.jpg
Kamran181.jpg
Kamran182.jpg
Kamran183.jpg
Kamran184.jpg
Kamran185.jpg
Kamran186.jpg
Kamran187.jpg
Kamran188.jpg
Kamran189.jpg
Kamran19.jpg
Kamran190.jpg
Kamran191.jpg
Kamran192.jpg
Kamran193.jpg
Kamran194.jpg
Kamran195.jpg
Kamran196.jpg
Kamran197.jpg
Kamran198.jpg
Kamran199.jpg
Kamran2.jpg
Kamran20.jpg
Kamran200.jpg
Kamran201.jpg
Kamran202.jpg
Kamran203.jpg
Kamran204.jpg
Kamran205.jpg
Kamran206.jpg
Kamran207.jpg
Kamran208.jpg
Kamran209.jpg
Kamran21.jpg
Kamran210.jpg
Kamran211.jpg
Kamran212.jpg
Kamran213.jpg
Kamran214.jpg
Kamran215.jpg
Kamran216.jpg
Kamran217.jpg
Kamran218.jpg
Kamran219.jpg
Kamran22.jpg
Kamran220.jpg
Kamran221.jpg
Kamran222.jpg
K

 70%|███████   | 875/1250 [00:02<00:00, 1145.84it/s]

Karthik22.jpg
Karthik220.jpg
Karthik221.jpg
Karthik222.jpg
Karthik223.jpg
Karthik224.jpg
Karthik225.jpg
Karthik226.jpg
Karthik227.jpg
Karthik228.jpg
Karthik229.jpg
Karthik23.jpg
Karthik230.jpg
Karthik231.jpg
Karthik232.jpg
Karthik233.jpg
Karthik234.jpg
Karthik235.jpg
Karthik236.jpg
Karthik237.jpg
Karthik238.jpg
Karthik239.jpg
Karthik24.jpg
Karthik240.jpg
Karthik241.jpg
Karthik242.jpg
Karthik243.jpg
Karthik244.jpg
Karthik245.jpg
Karthik246.jpg
Karthik247.jpg
Karthik248.jpg
Karthik249.jpg
Karthik25.jpg
Karthik250.jpg
Karthik26.jpg
Karthik27.jpg
Karthik28.jpg
Karthik29.jpg
Karthik3.jpg
Karthik30.jpg
Karthik31.jpg
Karthik32.jpg
Karthik33.jpg
Karthik34.jpg
Karthik35.jpg
Karthik36.jpg
Karthik37.jpg
Karthik38.jpg
Karthik39.jpg
Karthik4.jpg
Karthik40.jpg
Karthik41.jpg
Karthik42.jpg
Karthik43.jpg
Karthik44.jpg
Karthik45.jpg
Karthik46.jpg
Karthik47.jpg
Karthik48.jpg
Karthik49.jpg
Karthik5.jpg
Karthik50.jpg
Karthik51.jpg
Karthik52.jpg
Karthik53.jpg
Karthik54.jpg
Karthik55.jpg
Karthik56.jpg
Karthi

 91%|█████████ | 1134/1250 [00:02<00:00, 1217.72it/s]

Sruthi244.jpg
Sruthi245.jpg
Sruthi246.jpg
Sruthi247.jpg
Sruthi248.jpg
Sruthi249.jpg
Sruthi25.jpg
Sruthi250.jpg
Sruthi26.jpg
Sruthi27.jpg
Sruthi28.jpg
Sruthi29.jpg
Sruthi3.jpg
Sruthi30.jpg
Sruthi31.jpg
Sruthi32.jpg
Sruthi33.jpg
Sruthi34.jpg
Sruthi35.jpg
Sruthi36.jpg
Sruthi37.jpg
Sruthi38.jpg
Sruthi39.jpg
Sruthi4.jpg
Sruthi40.jpg
Sruthi41.jpg
Sruthi42.jpg
Sruthi43.jpg
Sruthi44.jpg
Sruthi45.jpg
Sruthi46.jpg
Sruthi47.jpg
Sruthi48.jpg
Sruthi49.jpg
Sruthi5.jpg
Sruthi50.jpg
Sruthi51.jpg
Sruthi52.jpg
Sruthi53.jpg
Sruthi54.jpg
Sruthi55.jpg
Sruthi56.jpg
Sruthi57.jpg
Sruthi58.jpg
Sruthi59.jpg
Sruthi6.jpg
Sruthi60.jpg
Sruthi61.jpg
Sruthi62.jpg
Sruthi63.jpg
Sruthi64.jpg
Sruthi65.jpg
Sruthi66.jpg
Sruthi67.jpg
Sruthi68.jpg
Sruthi69.jpg
Sruthi7.jpg
Sruthi70.jpg
Sruthi71.jpg
Sruthi72.jpg
Sruthi73.jpg
Sruthi74.jpg
Sruthi75.jpg
Sruthi76.jpg
Sruthi77.jpg
Sruthi78.jpg
Sruthi79.jpg
Sruthi8.jpg
Sruthi80.jpg
Sruthi81.jpg
Sruthi82.jpg
Sruthi83.jpg
Sruthi84.jpg
Sruthi85.jpg
Sruthi86.jpg
Sruthi87.jpg
Sruthi88.jp

100%|██████████| 1250/1250 [00:02<00:00, 541.90it/s] 


Vaibhav32.jpg
Vaibhav33.jpg
Vaibhav34.jpg
Vaibhav35.jpg
Vaibhav36.jpg
Vaibhav37.jpg
Vaibhav38.jpg
Vaibhav39.jpg
Vaibhav4.jpg
Vaibhav40.jpg
Vaibhav41.jpg
Vaibhav42.jpg
Vaibhav43.jpg
Vaibhav44.jpg
Vaibhav45.jpg
Vaibhav46.jpg
Vaibhav47.jpg
Vaibhav48.jpg
Vaibhav49.jpg
Vaibhav5.jpg
Vaibhav50.jpg
Vaibhav51.jpg
Vaibhav52.jpg
Vaibhav53.jpg
Vaibhav54.jpg
Vaibhav55.jpg
Vaibhav56.jpg
Vaibhav57.jpg
Vaibhav58.jpg
Vaibhav59.jpg
Vaibhav6.jpg
Vaibhav60.jpg
Vaibhav61.jpg
Vaibhav62.jpg
Vaibhav63.jpg
Vaibhav64.jpg
Vaibhav65.jpg
Vaibhav66.jpg
Vaibhav67.jpg
Vaibhav68.jpg
Vaibhav69.jpg
Vaibhav7.jpg
Vaibhav70.jpg
Vaibhav71.jpg
Vaibhav72.jpg
Vaibhav73.jpg
Vaibhav74.jpg
Vaibhav75.jpg
Vaibhav76.jpg
Vaibhav77.jpg
Vaibhav78.jpg
Vaibhav79.jpg
Vaibhav8.jpg
Vaibhav80.jpg
Vaibhav81.jpg
Vaibhav82.jpg
Vaibhav83.jpg
Vaibhav84.jpg
Vaibhav85.jpg
Vaibhav86.jpg
Vaibhav87.jpg
Vaibhav88.jpg
Vaibhav89.jpg
Vaibhav9.jpg
Vaibhav90.jpg
Vaibhav91.jpg
Vaibhav92.jpg
Vaibhav93.jpg
Vaibhav94.jpg
Vaibhav95.jpg
Vaibhav96.jpg
Vaibhav97.jp

In [10]:
train = data[:875]  
test = data[875:]
X_train = np.array([i[0] for i in train]).reshape(-1,50,50,1)
print(X_train.shape)
y_train = np.array([i[1] for i in train])
X_test = np.array([i[0] for i in test]).reshape(-1,50,50,1)
print(X_test.shape)
y_test = np.array([i[1] for i in test])
print(y_train.shape)
len(y_train)

# One-hot encode the labels for categorical crossentropy
# y_train = tf.keras.utils.to_categorical(y_train, num_classes=2)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes=2)

print(y_train)
print(y_train.shape)

(875, 50, 50, 1)
(375, 50, 50, 1)
(875, 5)
[[1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 ...
 [0 0 0 1 0]
 [0 0 1 0 0]
 [1 0 0 0 0]]
(875, 5)


In [16]:
import tensorflow as tf
from tensorflow.keras import layers, models



# Define the model
model = models.Sequential()

# Add layers to the model
model.add(layers.Conv2D(32, (5, 5), activation='relu', input_shape=(50, 50, 1), padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(128, (5, 5), activation='relu', padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(32, (5, 5), activation='relu', padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

# Flatten the output to feed into fully connected layers
model.add(layers.Flatten())
model.add(layers.Dense(1024, activation='relu'))
model.add(layers.Dropout(0.8))
model.add(layers.Dense(5, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# y_train = tf.keras.utils.to_categorical(y_train, num_classes=2)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes=2)

# Fit the model
# class_weights = {0: 1.5, 1: 1.5, 2: 1.5, 3: 1.5, 4: 3}  # Higher weight for "Intruder"
model.fit(X_train, y_train, class_weight=class_weights, epochs=12, validation_data=(X_test, y_test), batch_size=32)

# convnet = fully_connected(convnet, 1024, activation='relu')
# convnet = dropout(convnet, 0.8)
# convnet = fully_connected(convnet, 2, activation='softmax')
# convnet = regression(convnet, optimizer='adam', learning_rate = 0.001, loss='categorical_crossentropy')
# model = tflearn.DNN(convnet, tensorboard_verbose=1)
# model.fit(X_train, y_train, n_epoch=10, validation_set=(X_test, y_test), show_metric = True, run_id="FRS" )
# model.save('face_recognition_model.h5')
# print("Model saved as 'face_recognition_model.h5'")


Epoch 1/12


c:\Users\rbvai\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


28/28 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.2078 - loss: 4.0052 - val_accuracy: 0.1947 - val_loss: 1.3782
Epoch 2/12
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.4334 - loss: 2.0143 - val_accuracy: 0.7947 - val_loss: 0.5393
Epoch 3/12
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - accuracy: 0.8202 - loss: 0.8359 - val_accuracy: 0.9733 - val_loss: 0.1525
Epoch 4/12
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9657 - loss: 0.2676 - val_accuracy: 0.9813 - val_loss: 0.1162
Epoch 5/12
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - accuracy: 0.9786 - loss: 0.1669 - val_accuracy: 0.9893 - val_loss: 0.0301
Epoch 6/12
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 0.9818 - loss: 0.0839 - val_accuracy: 0.9893 - val_loss: 0.0341
Epoch 7/12
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9907 - loss: 0.0493 - val_accuracy: 0.9920 - val_loss: 0.0221
Epoch 8/12
28/28 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9830 - loss: 0.1028 - val_accuracy: 0.9787 - val_loss: 0.

In [17]:
model.save("face_model.keras")

In [18]:
def data_for_visualization():
    Vdata = []
    for img in tqdm(os.listdir(r"C:\Vaibhav Data\Proffesional\Engineering\NHCE\Sem 6\Mini Project - III\Face_recog\Images for visualization")):
        path = os.path.join(r"C:\Vaibhav Data\Proffesional\Engineering\NHCE\Sem 6\Mini Project - III\Face_recog\Images for visualization", img)
        img_num = img.split('.')[0] 
        img_data = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img_data = cv2.resize(img_data, (50,50))
        Vdata.append([np.array(img_data), img_num])
    shuffle(Vdata)
    return Vdata

In [19]:
import matplotlib.pyplot as plt   # installation command: pip install matplotlib
Vdata = data_for_visualization()
fig = plt.figure(figsize=(20,20))
for num, data in enumerate(Vdata[:20]):
    img_data = data[0]
    y = fig.add_subplot(5,5, num+1)
    image = img_data
    data = img_data.reshape(1,50,50,1)
    model_out = model.predict([data])[0]
     
    if np.argmax(model_out) == 0:
        my_label = 'Vaibhav'
    elif np.argmax(model_out) == 1:
        my_label = 'Sruthi'
    elif np.argmax(model_out) == 2:
        my_label = 'Kamran'
    elif np.argmax(model_out) == 3:
        my_label = 'Karthik'
    elif np.argmax(model_out) == 4:
        my_label = 'Intruder'
         
    y.imshow(image, cmap='gray')
    
    # plt.title(my_label)
    plt.title(str(model_out[np.argmax(model_out)]*100))
    y.axes.get_xaxis().set_visible(False)
    y.axes.get_yaxis().set_visible(False)
plt.show()

0it [00:00, ?it/s]


<Figure size 2000x2000 with 0 Axes>

In [20]:
import cv2
import tensorflow as tf
import numpy as np

face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

model = tf.keras.models.load_model("face_model.keras")

def real_time_recognition():
    cap = cv2.VideoCapture(1)
    
    while True:
        ret, frame = cap.read()
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = face_classifier.detectMultiScale(gray, 1.3, 5) 
        # confidence = model.predict([data])[0]
    
        for (x, y, w, h) in faces:
            cropped_face = gray[y:y+h, x:x+w]
            cropped_face = cv2.resize(cropped_face, (50, 50)).reshape(1, 50, 50, 1)

            model_out = model.predict(cropped_face)[0]

            if np.argmax(model_out) == 0:
                label = 'Vaibhav'
            elif np.argmax(model_out) == 1:
                label = 'Sruthi'
            elif np.argmax(model_out) == 2:
                label = 'Kamran'
            elif np.argmax(model_out) == 3:
                label = 'Karthik'
            elif np.argmax(model_out) == 4:
                label = 'Intruder'
            
            
            
            cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
            cv2.putText(frame, label, (x+4, y-6), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 0, 0), 2)
            cv2.putText(frame, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 0, 255), 2)
            cv2.putText(frame, str(model_out[np.argmax(model_out)]*100), (x, y-40), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 0), 2)
            
        cv2.imshow('Real-Time Face Recognition', frame)

        # if confidence >= 70 and label != "Unknown":
        #         print(f"Recognized {label}. Initiating fingerprint verification...")
        #         cap.release()
        #         cv2.destroyAllWindows()
        #         time.sleep(10)
        #         return fingerprint_verification()


        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

real_time_recognition()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━