In [46]:
import cv2
import time

In [47]:
def generate_dataset(Name):
    face_classifier = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
    
    def face_cropped(img):
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = face_classifier.detectMultiScale(gray, 1.3, 5)
        
        if len(faces) == 0:
            return None
        for (x, y, w, h) in faces:
            cropped_face = img[y:y+h, x:x+w]
        return cropped_face
    
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("Error: Could not open video capture")
        return
    
    img_id = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            print("Failed to capture image")
            break
        
        cropped_face = face_cropped(frame)
        if cropped_face is not None:
            img_id += 1
            face = cv2.resize(cropped_face, (200, 200))
            face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)
            file_name_path = "C:/Vaibhav Data/Proffesional/Engineering/NHCE/Sem 6/Mini Project - III/Face_recog/data/"+ Name + str(img_id) + ".jpg"
            cv2.imwrite(file_name_path, face)
            cv2.putText(face, str(img_id), (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)
            
            cv2.imshow("Cropped_Face", face)
            if cv2.waitKey(1) == 13 or img_id == 200:
                break
        else:
            cv2.imshow("Camera Feed", frame)
            if cv2.waitKey(1) == 13:
                break
    
    cap.release()
    cv2.destroyAllWindows()
    print("Collecting samples is completed.")

generate_dataset("Vaibhav")
time.sleep(10)
generate_dataset("Sruthi")

In [48]:
import numpy as np

In [49]:
import os

def find_images(directory, extensions=None):
    """
    Finds all images in a given directory with specified extensions.
    
    Args:
        directory (str): Path to the directory to search for images.
        extensions (list): List of valid image file extensions (default: common formats).
    
    Returns:
        list: List of paths to image files.
    """
    if extensions is None:
        # Default to common image extensions
        extensions = ['.jpg', '.jpeg', '.png']
    
    # Normalize extensions to lowercase
    extensions = [ext.lower() for ext in extensions]
    
    # List to hold image paths
    image_files = []
    
    # Walk through the directory
    for root, _, files in os.walk(directory):
        for file in files:
            if os.path.splitext(file)[1].lower() in extensions:
                image_files.append(os.path.join(root, file))
    
    return image_files

# Example usage
directory_path = "indian_faces"  # Replace with your directory path
images = find_images(directory_path)

print("Found Images:")
count = 0
for image in images:
    count += 1
    print(count, image)



Found Images:
1 indian_faces\06298d548430d752925da79fdc2f8f32.jpg
2 indian_faces\1200px-Old_Indian_man2C_Bihar2C_India2C_2012.jpg
3 indian_faces\1670649912-3704.jpeg
4 indian_faces\2008-10-06_IMG_8607.jpg
5 indian_faces\2008-10-14_IMG_9489.jpg
6 indian_faces\2560px-Indian_male_face.jpg
7 indian_faces\2807.jpg
8 indian_faces\360_F_463221858_50KkvfxxovUaMNlilCmUxrOnTqSpzAlP.jpg
9 indian_faces\360_F_620730419_9cf73do9dxGaNJCztZPETHdB5bdrbW5D.jpg
10 indian_faces\5da8768c07eb3db7dbf5f394ab4444a6.jpg
11 indian_faces\847aa4ea94e646a239324307bc3b4236.jpg
12 indian_faces\91808573.jpg
13 indian_faces\a-face-young-handsome-indian-man-isolated-against-white-background-131186211.jpg
14 indian_faces\AF2bZyiAgReabunzr39lBthF2McS20v-ZJ1X9LClybZ5iILYIEnSs64-c-mo.jpg
15 indian_faces\asian-man-indian-origin-7252735.jpg
16 indian_faces\bc976b2596bbb9e5ca0e9a9ad9839be4.png
17 indian_faces\boy-happy-mood-asian-smiling-260nw-2374333277.jpg
18 indian_faces\c8b276ea169aecb66cd0b7e6ad114274.jpg
19 indian_faces\

In [50]:
import cv2
import os

def extract_faces(image_path, output_dir, count,resize_dim=(200, 200)):
    """
    Extracts faces from an image, converts them to grayscale, resizes them, 
    and saves them as 50x50 images.
    
    Args:
        image_path (str): Path to the input image.
        output_dir (str): Directory to save the extracted face images.
        resize_dim (tuple): Dimensions to resize the face images (default: (50, 50)).
    """
    # Load the image
    image = cv2.imread(image_path)
    if image is None:
        print(f"Error: Unable to load image {image_path}")
        return
    
    # Convert to grayscale for face detection
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    # Load pre-trained Haar Cascade for face detection
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    
    # Detect faces in the image
    faces = face_cascade.detectMultiScale(gray_image, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))
    
    if len(faces) == 0:
        print("No faces detected in the image.")
        return
    
    # Ensure the output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    # Process each detected face
    for i, (x, y, w, h) in enumerate(faces):
        # Extract the face region
        face = gray_image[y:y+h, x:x+w]
        
        # Resize to the desired dimensions
        resized_face = cv2.resize(face, resize_dim)
        
        # Save the resized grayscale face image
        output_path = os.path.join(output_dir, f"intruder_{count+i+1}.png")
        cv2.imwrite(output_path, resized_face)
        print(f"Saved face {i+1} to {output_path}")

directory_path = "indian_faces"  # Replace with your directory path
images = find_images(directory_path)

print("Found Images:")
for idx, image in enumerate(images):
    extract_faces(image, "data", count=idx+1)

Found Images:
Saved face 1 to data\intruder_2.png
Saved face 2 to data\intruder_3.png
Saved face 1 to data\intruder_3.png
Saved face 2 to data\intruder_4.png
Saved face 1 to data\intruder_4.png
Saved face 1 to data\intruder_5.png
Saved face 1 to data\intruder_6.png
Saved face 1 to data\intruder_7.png
Saved face 2 to data\intruder_8.png
Saved face 3 to data\intruder_9.png
Saved face 4 to data\intruder_10.png
Saved face 5 to data\intruder_11.png
Saved face 6 to data\intruder_12.png
Saved face 7 to data\intruder_13.png
Saved face 8 to data\intruder_14.png
Saved face 9 to data\intruder_15.png
Saved face 10 to data\intruder_16.png
Saved face 11 to data\intruder_17.png
Saved face 12 to data\intruder_18.png
Saved face 13 to data\intruder_19.png
Saved face 14 to data\intruder_20.png
Saved face 15 to data\intruder_21.png
Saved face 16 to data\intruder_22.png
Saved face 17 to data\intruder_23.png
Saved face 18 to data\intruder_24.png
Saved face 19 to data\intruder_25.png
Saved face 20 to data\in

In [51]:
# def my_label(image_name):
#     name = image_name.split('.')[0] 
    
#     if name=="Vaibhav":
#         return np.array([1,0])
#     elif name=="Sruthi":
#         return np.array([0,1])

def my_label(image_name):
    name = image_name.split('.')[0]  # Extract the part before the file extension
    
    if name.startswith("Vaibhav"):
        return np.array([1, 0, 0])
    elif name.startswith("Sruthi"):
        return np.array([0, 1, 0])
    else:
        return np.array([0, 0, 1])


In [52]:
import os
from random import shuffle
from tqdm import tqdm

In [53]:
def my_data():
    data = []
    for img in tqdm(os.listdir("data")):
        path=os.path.join("data",img)
        img_data = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img_data = cv2.resize(img_data, (50,50))
        data.append([np.array(img_data), my_label(img)])
        print(img)
    shuffle(data)  
    return data


In [54]:
data = my_data()
print(data)

  3%|▎         | 17/513 [00:00<00:03, 160.54it/s]

intruder_10.png
intruder_100.png
intruder_101.png
intruder_102.png
intruder_103.png
intruder_104.png
intruder_105.png
intruder_106.png
intruder_107.png
intruder_108.png
intruder_109.png
intruder_11.png
intruder_110.png
intruder_111.png
intruder_112.png
intruder_113.png
intruder_114.png
intruder_115.png
intruder_116.png
intruder_117.png
intruder_12.png
intruder_13.png
intruder_14.png
intruder_15.png
intruder_16.png
intruder_17.png
intruder_18.png
intruder_19.png
intruder_2.png
intruder_20.png
intruder_21.png
intruder_22.png


 10%|▉         | 51/513 [00:00<00:02, 159.01it/s]

intruder_23.png
intruder_24.png
intruder_25.png
intruder_26.png
intruder_27.png
intruder_28.png
intruder_29.png
intruder_3.png
intruder_30.png
intruder_31.png
intruder_32.png
intruder_33.png
intruder_34.png
intruder_35.png
intruder_36.png
intruder_37.png
intruder_38.png
intruder_39.png
intruder_4.png
intruder_40.png
intruder_43.png
intruder_44.png
intruder_45.png
intruder_46.png
intruder_47.png
intruder_48.png
intruder_49.png
intruder_5.png
intruder_50.png
intruder_51.png
intruder_52.png
intruder_53.png


 17%|█▋        | 85/513 [00:00<00:02, 159.29it/s]

intruder_54.png
intruder_55.png
intruder_56.png
intruder_57.png
intruder_58.png
intruder_59.png
intruder_6.png
intruder_60.png
intruder_61.png
intruder_62.png
intruder_63.png
intruder_64.png
intruder_65.png
intruder_66.png
intruder_67.png
intruder_68.png
intruder_69.png
intruder_7.png
intruder_70.png
intruder_71.png
intruder_72.png
intruder_73.png
intruder_74.png
intruder_75.png
intruder_76.png
intruder_77.png
intruder_78.png
intruder_79.png
intruder_8.png
intruder_81.png
intruder_82.png
intruder_83.png
intruder_84.png
intruder_85.png


 23%|██▎       | 119/513 [00:00<00:02, 161.01it/s]

intruder_86.png
intruder_87.png
intruder_88.png
intruder_89.png
intruder_9.png
intruder_90.png
intruder_91.png
intruder_92.png
intruder_93.png
intruder_94.png
intruder_95.png
intruder_96.png
intruder_97.png
intruder_98.png
intruder_99.png
Sruthi1.jpg
Sruthi10.jpg
Sruthi100.jpg
Sruthi101.jpg
Sruthi102.jpg
Sruthi103.jpg
Sruthi104.jpg
Sruthi105.jpg
Sruthi106.jpg
Sruthi107.jpg
Sruthi108.jpg
Sruthi109.jpg
Sruthi11.jpg
Sruthi110.jpg
Sruthi111.jpg
Sruthi112.jpg
Sruthi113.jpg
Sruthi114.jpg
Sruthi115.jpg


 30%|███       | 154/513 [00:00<00:02, 164.71it/s]

Sruthi116.jpg
Sruthi117.jpg
Sruthi118.jpg
Sruthi119.jpg
Sruthi12.jpg
Sruthi120.jpg
Sruthi121.jpg
Sruthi122.jpg
Sruthi123.jpg
Sruthi124.jpg
Sruthi125.jpg
Sruthi126.jpg
Sruthi127.jpg
Sruthi128.jpg
Sruthi129.jpg
Sruthi13.jpg
Sruthi130.jpg
Sruthi131.jpg
Sruthi132.jpg
Sruthi133.jpg
Sruthi134.jpg
Sruthi135.jpg
Sruthi136.jpg
Sruthi137.jpg
Sruthi138.jpg
Sruthi139.jpg
Sruthi14.jpg
Sruthi140.jpg
Sruthi141.jpg
Sruthi142.jpg
Sruthi143.jpg
Sruthi144.jpg
Sruthi145.jpg
Sruthi146.jpg
Sruthi147.jpg
Sruthi148.jpg


 37%|███▋      | 191/513 [00:01<00:01, 170.76it/s]

Sruthi149.jpg
Sruthi15.jpg
Sruthi150.jpg
Sruthi151.jpg
Sruthi152.jpg
Sruthi153.jpg
Sruthi154.jpg
Sruthi155.jpg
Sruthi156.jpg
Sruthi157.jpg
Sruthi158.jpg
Sruthi159.jpg
Sruthi16.jpg
Sruthi160.jpg
Sruthi161.jpg
Sruthi162.jpg
Sruthi163.jpg
Sruthi164.jpg
Sruthi165.jpg
Sruthi166.jpg
Sruthi167.jpg
Sruthi168.jpg
Sruthi169.jpg
Sruthi17.jpg
Sruthi170.jpg
Sruthi171.jpg
Sruthi172.jpg
Sruthi173.jpg
Sruthi174.jpg
Sruthi175.jpg
Sruthi176.jpg
Sruthi177.jpg
Sruthi178.jpg
Sruthi179.jpg
Sruthi18.jpg
Sruthi180.jpg
Sruthi181.jpg
Sruthi182.jpg
Sruthi183.jpg


 44%|████▍     | 227/513 [00:01<00:01, 169.43it/s]

Sruthi184.jpg
Sruthi185.jpg
Sruthi186.jpg
Sruthi187.jpg
Sruthi188.jpg
Sruthi189.jpg
Sruthi19.jpg
Sruthi190.jpg
Sruthi191.jpg
Sruthi192.jpg
Sruthi193.jpg
Sruthi194.jpg
Sruthi195.jpg
Sruthi196.jpg
Sruthi197.jpg
Sruthi198.jpg
Sruthi199.jpg
Sruthi2.jpg
Sruthi20.jpg
Sruthi200.jpg
Sruthi21.jpg
Sruthi22.jpg
Sruthi23.jpg
Sruthi24.jpg
Sruthi25.jpg
Sruthi26.jpg
Sruthi27.jpg
Sruthi28.jpg
Sruthi29.jpg
Sruthi3.jpg
Sruthi30.jpg
Sruthi31.jpg
Sruthi32.jpg
Sruthi33.jpg


 51%|█████▏    | 263/513 [00:01<00:01, 170.27it/s]

Sruthi34.jpg
Sruthi35.jpg
Sruthi36.jpg
Sruthi37.jpg
Sruthi38.jpg
Sruthi39.jpg
Sruthi4.jpg
Sruthi40.jpg
Sruthi41.jpg
Sruthi42.jpg
Sruthi43.jpg
Sruthi44.jpg
Sruthi45.jpg
Sruthi46.jpg
Sruthi47.jpg
Sruthi48.jpg
Sruthi49.jpg
Sruthi5.jpg
Sruthi50.jpg
Sruthi51.jpg
Sruthi52.jpg
Sruthi53.jpg
Sruthi54.jpg
Sruthi55.jpg
Sruthi56.jpg
Sruthi57.jpg
Sruthi58.jpg
Sruthi59.jpg
Sruthi6.jpg
Sruthi60.jpg
Sruthi61.jpg
Sruthi62.jpg
Sruthi63.jpg
Sruthi64.jpg
Sruthi65.jpg
Sruthi66.jpg
Sruthi67.jpg
Sruthi68.jpg


 59%|█████▊    | 301/513 [00:01<00:01, 176.05it/s]

Sruthi69.jpg
Sruthi7.jpg
Sruthi70.jpg
Sruthi71.jpg
Sruthi72.jpg
Sruthi73.jpg
Sruthi74.jpg
Sruthi75.jpg
Sruthi76.jpg
Sruthi77.jpg
Sruthi78.jpg
Sruthi79.jpg
Sruthi8.jpg
Sruthi80.jpg
Sruthi81.jpg
Sruthi82.jpg
Sruthi83.jpg
Sruthi84.jpg
Sruthi85.jpg
Sruthi86.jpg
Sruthi87.jpg
Sruthi88.jpg
Sruthi89.jpg
Sruthi9.jpg
Sruthi90.jpg
Sruthi91.jpg
Sruthi92.jpg
Sruthi93.jpg
Sruthi94.jpg
Sruthi95.jpg
Sruthi96.jpg
Sruthi97.jpg
Sruthi98.jpg
Sruthi99.jpg
Vaibhav1.jpg
Vaibhav10.jpg


 66%|██████▌   | 337/513 [00:01<00:01, 174.29it/s]

Vaibhav100.jpg
Vaibhav101.jpg
Vaibhav102.jpg
Vaibhav103.jpg
Vaibhav104.jpg
Vaibhav105.jpg
Vaibhav106.jpg
Vaibhav107.jpg
Vaibhav108.jpg
Vaibhav109.jpg
Vaibhav11.jpg
Vaibhav110.jpg
Vaibhav111.jpg
Vaibhav112.jpg
Vaibhav113.jpg
Vaibhav114.jpg
Vaibhav115.jpg
Vaibhav116.jpg
Vaibhav117.jpg
Vaibhav118.jpg
Vaibhav119.jpg
Vaibhav12.jpg
Vaibhav120.jpg
Vaibhav121.jpg
Vaibhav122.jpg
Vaibhav123.jpg
Vaibhav124.jpg
Vaibhav125.jpg
Vaibhav126.jpg
Vaibhav127.jpg
Vaibhav128.jpg
Vaibhav129.jpg
Vaibhav13.jpg
Vaibhav130.jpg
Vaibhav131.jpg
Vaibhav132.jpg
Vaibhav133.jpg


 73%|███████▎  | 374/513 [00:02<00:00, 176.77it/s]

Vaibhav134.jpg
Vaibhav135.jpg
Vaibhav136.jpg
Vaibhav137.jpg
Vaibhav138.jpg
Vaibhav139.jpg
Vaibhav14.jpg
Vaibhav140.jpg
Vaibhav141.jpg
Vaibhav142.jpg
Vaibhav143.jpg
Vaibhav144.jpg
Vaibhav145.jpg
Vaibhav146.jpg
Vaibhav147.jpg
Vaibhav148.jpg
Vaibhav149.jpg
Vaibhav15.jpg
Vaibhav150.jpg
Vaibhav151.jpg
Vaibhav152.jpg
Vaibhav153.jpg
Vaibhav154.jpg
Vaibhav155.jpg
Vaibhav156.jpg
Vaibhav157.jpg
Vaibhav158.jpg
Vaibhav159.jpg
Vaibhav16.jpg
Vaibhav160.jpg
Vaibhav161.jpg
Vaibhav162.jpg
Vaibhav163.jpg
Vaibhav164.jpg
Vaibhav165.jpg
Vaibhav166.jpg
Vaibhav167.jpg
Vaibhav168.jpg
Vaibhav169.jpg


 80%|████████  | 411/513 [00:02<00:00, 176.33it/s]

Vaibhav17.jpg
Vaibhav170.jpg
Vaibhav171.jpg
Vaibhav172.jpg
Vaibhav173.jpg
Vaibhav174.jpg
Vaibhav175.jpg
Vaibhav176.jpg
Vaibhav177.jpg
Vaibhav178.jpg
Vaibhav179.jpg
Vaibhav18.jpg
Vaibhav180.jpg
Vaibhav181.jpg
Vaibhav182.jpg
Vaibhav183.jpg
Vaibhav184.jpg
Vaibhav185.jpg
Vaibhav186.jpg
Vaibhav187.jpg
Vaibhav188.jpg
Vaibhav189.jpg
Vaibhav19.jpg
Vaibhav190.jpg
Vaibhav191.jpg
Vaibhav192.jpg
Vaibhav193.jpg
Vaibhav194.jpg
Vaibhav195.jpg
Vaibhav196.jpg
Vaibhav197.jpg
Vaibhav198.jpg


 87%|████████▋ | 446/513 [00:02<00:00, 153.32it/s]

Vaibhav199.jpg
Vaibhav2.jpg
Vaibhav20.jpg
Vaibhav200.jpg
Vaibhav21.jpg
Vaibhav22.jpg
Vaibhav23.jpg
Vaibhav24.jpg
Vaibhav25.jpg
Vaibhav26.jpg
Vaibhav27.jpg
Vaibhav28.jpg
Vaibhav29.jpg
Vaibhav3.jpg
Vaibhav30.jpg
Vaibhav31.jpg
Vaibhav32.jpg
Vaibhav33.jpg
Vaibhav34.jpg
Vaibhav35.jpg
Vaibhav36.jpg
Vaibhav37.jpg
Vaibhav38.jpg
Vaibhav39.jpg
Vaibhav4.jpg
Vaibhav40.jpg
Vaibhav41.jpg
Vaibhav42.jpg
Vaibhav43.jpg
Vaibhav44.jpg
Vaibhav45.jpg


 93%|█████████▎| 478/513 [00:02<00:00, 147.26it/s]

Vaibhav46.jpg
Vaibhav47.jpg
Vaibhav48.jpg
Vaibhav49.jpg
Vaibhav5.jpg
Vaibhav50.jpg
Vaibhav51.jpg
Vaibhav52.jpg
Vaibhav53.jpg
Vaibhav54.jpg
Vaibhav55.jpg
Vaibhav56.jpg
Vaibhav57.jpg
Vaibhav58.jpg
Vaibhav59.jpg
Vaibhav6.jpg
Vaibhav60.jpg
Vaibhav61.jpg
Vaibhav62.jpg
Vaibhav63.jpg
Vaibhav64.jpg
Vaibhav65.jpg
Vaibhav66.jpg
Vaibhav67.jpg
Vaibhav68.jpg
Vaibhav69.jpg
Vaibhav7.jpg
Vaibhav70.jpg
Vaibhav71.jpg
Vaibhav72.jpg


 99%|█████████▉| 508/513 [00:03<00:00, 142.42it/s]

Vaibhav73.jpg
Vaibhav74.jpg
Vaibhav75.jpg
Vaibhav76.jpg
Vaibhav77.jpg
Vaibhav78.jpg
Vaibhav79.jpg
Vaibhav8.jpg
Vaibhav80.jpg
Vaibhav81.jpg
Vaibhav82.jpg
Vaibhav83.jpg
Vaibhav84.jpg
Vaibhav85.jpg
Vaibhav86.jpg
Vaibhav87.jpg
Vaibhav88.jpg
Vaibhav89.jpg
Vaibhav9.jpg
Vaibhav90.jpg
Vaibhav91.jpg
Vaibhav92.jpg
Vaibhav93.jpg
Vaibhav94.jpg
Vaibhav95.jpg
Vaibhav96.jpg
Vaibhav97.jpg
Vaibhav98.jpg


100%|██████████| 513/513 [00:03<00:00, 162.61it/s]


Vaibhav99.jpg
[[array([[ 59,  57,  62, ...,  86, 128, 150],
       [ 62,  56,  57, ..., 105, 192, 245],
       [ 64,  58,  53, ..., 145, 246, 254],
       ...,
       [ 71,  68,  69, ...,  38,  41,  40],
       [ 72,  69,  66, ...,  34,  35,  39],
       [ 69,  69,  65, ...,  28,  31,  36]], dtype=uint8), array([1, 0, 0])], [array([[  4,  11,  22, ..., 101,  91,  24],
       [  4,  14,  20, ...,  60,  44,  24],
       [  5,  13,  16, ...,  19,  18,  18],
       ...,
       [ 87,  92,  96, ...,  35,  31,  22],
       [ 85,  94,  97, ...,  32,  28,  21],
       [ 80,  88,  94, ...,  27,  25,  20]], dtype=uint8), array([0, 1, 0])], [array([[ 40,  54,  57, ...,  79,  95,  81],
       [ 49,  49,  50, ..., 145, 146, 137],
       [ 54,  54,  60, ..., 156, 153, 153],
       ...,
       [106, 106, 113, ...,  44,  42,  48],
       [106, 105, 113, ...,  46,  45,  47],
       [107, 105, 106, ...,  46,  42,  46]], dtype=uint8), array([0, 1, 0])], [array([[174, 111,  75, ..., 242, 242, 241],
       

In [55]:
train = data[:400]  
test = data[400:]
X_train = np.array([i[0] for i in train]).reshape(-1,50,50,1)
print(X_train.shape)
y_train = np.array([i[1] for i in train])
X_test = np.array([i[0] for i in test]).reshape(-1,50,50,1)
print(X_test.shape)
y_test = np.array([i[1] for i in test])
print(y_train.shape)
len(y_train)

# One-hot encode the labels for categorical crossentropy
# y_train = tf.keras.utils.to_categorical(y_train, num_classes=2)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes=2)

print(y_train)
print(y_train.shape)

(400, 50, 50, 1)
(113, 50, 50, 1)
(400, 3)
[[1 0 0]
 [0 1 0]
 [0 1 0]
 ...
 [0 1 0]
 [1 0 0]
 [0 0 1]]
(400, 3)


In [56]:
import tensorflow as tf
from tensorflow.keras import layers, models



# Define the model
model = models.Sequential()

# Add layers to the model
model.add(layers.Conv2D(32, (5, 5), activation='relu', input_shape=(50, 50, 1), padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(128, (5, 5), activation='relu', padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(32, (5, 5), activation='relu', padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

# Flatten the output to feed into fully connected layers
model.add(layers.Flatten())
model.add(layers.Dense(1024, activation='relu'))
model.add(layers.Dropout(0.8))
model.add(layers.Dense(3, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# y_train = tf.keras.utils.to_categorical(y_train, num_classes=2)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes=2)

# Fit the model

model.fit(X_train, y_train, epochs=12, validation_data=(X_test, y_test), batch_size=32)

# convnet = fully_connected(convnet, 1024, activation='relu')
# convnet = dropout(convnet, 0.8)
# convnet = fully_connected(convnet, 2, activation='softmax')
# convnet = regression(convnet, optimizer='adam', learning_rate = 0.001, loss='categorical_crossentropy')
# model = tflearn.DNN(convnet, tensorboard_verbose=1)
# model.fit(X_train, y_train, n_epoch=10, validation_set=(X_test, y_test), show_metric = True, run_id="FRS" )
# model.save('face_recognition_model.h5')
# print("Model saved as 'face_recognition_model.h5'")


Epoch 1/12
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 57ms/step - accuracy: 0.3252 - loss: 2.0827 - val_accuracy: 0.7257 - val_loss: 1.0465
Epoch 2/12
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 0.5881 - loss: 0.9489 - val_accuracy: 0.7611 - val_loss: 0.6363
Epoch 3/12
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.7877 - loss: 0.5639 - val_accuracy: 0.9469 - val_loss: 0.1852
Epoch 4/12
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 46ms/step - accuracy: 0.9131 - loss: 0.2409 - val_accuracy: 0.9027 - val_loss: 0.3155
Epoch 5/12
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9379 - loss: 0.1969 - val_accuracy: 0.9558 - val_loss: 0.1231
Epoch 6/12
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9653 - loss: 0.1141 - val_accuracy: 0.9558 - val_loss: 0.1445
Epoch 7/12
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9914 - loss: 0.0366 - val_accuracy: 0.9735 - val_loss: 0.1262
Epoch 8/12
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 45ms/step - accuracy: 0.9968 - loss: 0.0145 - val_accuracy: 0.9912 - v

In [57]:
model.save("face_model.keras")

In [58]:
def data_for_visualization():
    Vdata = []
    for img in tqdm(os.listdir(r"C:\Vaibhav Data\Proffesional\Engineering\NHCE\Sem 6\Mini Project - III\Face_recog\Images for visualization")):
        path = os.path.join(r"C:\Vaibhav Data\Proffesional\Engineering\NHCE\Sem 6\Mini Project - III\Face_recog\Images for visualization", img)
        img_num = img.split('.')[0] 
        img_data = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img_data = cv2.resize(img_data, (50,50))
        Vdata.append([np.array(img_data), img_num])
    shuffle(Vdata)
    return Vdata

In [59]:
import matplotlib.pyplot as plt   # installation command: pip install matplotlib
Vdata = data_for_visualization()
fig = plt.figure(figsize=(20,20))
for num, data in enumerate(Vdata[:20]):
    img_data = data[0]
    y = fig.add_subplot(5,5, num+1)
    image = img_data
    data = img_data.reshape(1,50,50,1)
    model_out = model.predict([data])[0]
     
    if np.argmax(model_out) == 0:
        my_label = 'Vaibhav'
    elif np.argmax(model_out) == 1:
        my_label = 'Sruthi'
    
         
    y.imshow(image, cmap='gray')
    
    # plt.title(my_label)
    plt.title(str(model_out[np.argmax(model_out)]*100))
    y.axes.get_xaxis().set_visible(False)
    y.axes.get_yaxis().set_visible(False)
plt.show()

0it [00:00, ?it/s]


<Figure size 2000x2000 with 0 Axes>

In [60]:
import cv2
import tensorflow as tf
import numpy as np

face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

model = tf.keras.models.load_model("face_model.keras")

def real_time_recognition():
    cap = cv2.VideoCapture(0)
    
    while True:
        ret, frame = cap.read()
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = face_classifier.detectMultiScale(gray, 1.3, 5) 
        # confidence = model.predict([data])[0]
    
        for (x, y, w, h) in faces:
            cropped_face = gray[y:y+h, x:x+w]
            cropped_face = cv2.resize(cropped_face, (50, 50)).reshape(1, 50, 50, 1)

            model_out = model.predict(cropped_face)[0]

            if np.argmax(model_out) == 0:
                label = 'Vaibhav'
            elif np.argmax(model_out) == 1:
                label = 'Sruthi'
            elif np.argmax(model_out) == 2:
                label = "Intruder"
            
            
            
            cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
            cv2.putText(frame, label, (x+4, y-6), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 0, 0), 2)
            cv2.putText(frame, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 0, 255), 2)
            cv2.putText(frame, str(model_out[np.argmax(model_out)]*100), (x, y-40), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 0), 2)
            
        cv2.imshow('Real-Time Face Recognition', frame)

        # if confidence >= 70 and label != "Unknown":
        #         print(f"Recognized {label}. Initiating fingerprint verification...")
        #         cap.release()
        #         cv2.destroyAllWindows()
        #         time.sleep(10)
        #         return fingerprint_verification()


        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

real_time_recognition()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━

In [10]:
import cv2
import tensorflow as tf
from serial import Serial
import numpy as np

face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

model = tf.keras.models.load_model("face_model.keras")

# Connect to Arduino
arduino = Serial('COM9', baudrate=9600, timeout=1)  # Replace 'COM9' with your Arduino port
print("Connected to Arduino on COM9")

# Haar Cascade for face detection
face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
print("Loaded Haar Cascade for face detection")



def fingerprint_verification():
    """Ask Arduino to verify fingerprint."""
    print("Waiting for fingerprint...")
    arduino.write(b'F')  # Command Arduino to verify fingerprint
    while True:
        response = arduino.readline().decode().strip()
        print(f"Arduino response: {response}")  # Debugging print
        if response == "Fingerprint matched":
            print("Fingerprint matched! Unlocking solenoid lock...")
            arduino.write(b'U')  # Unlock command
            return True
        elif response == "Fingerprint not matched":
            print("Fingerprint not matched. Access denied.")
            return False

def real_time_recognition():
    cap = cv2.VideoCapture(0)
    
    while True:
        ret, frame = cap.read()
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = face_classifier.detectMultiScale(gray, 1.3, 5) 
        confidence = model.predict([data])[0]
    
        for (x, y, w, h) in faces:
            cropped_face = gray[y:y+h, x:x+w]
            cropped_face = cv2.resize(cropped_face, (50, 50)).reshape(1, 50, 50, 1)

            model_out = model.predict(cropped_face)[0]

            if np.argmax(model_out) == 0:
                label = 'Vaibhav'
            elif np.argmax(model_out) == 1:
                label = 'Sruthi'
            elif np.argmax(model_out) == 2:
                label = "Intruder"
            
            
            
            cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
            cv2.putText(frame, label, (x+4, y-6), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 0, 0), 2)
            cv2.putText(frame, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 0, 255), 2)
            cv2.putText(frame, str(model_out[np.argmax(model_out)]*100), (x, y-40), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 0), 2)
            
        cv2.imshow('Real-Time Face Recognition', frame)

        if confidence >= 70 and label != "Unknown":
                print(f"Recognized {label}. Initiating fingerprint verification...")
                cap.release()
                cv2.destroyAllWindows()
                time.sleep(10)
                return fingerprint_verification()


        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()
    return False


def check_motion_and_recognize_face():
    """Main function to detect motion, recognize face, and unlock lock."""
    print("Starting motion detection and face recognition...")
    try:
        while True:
            arduino.write(b'M')  # Send 'M' to Arduino to check motion
            response = arduino.readline().decode().strip()
            print(f"Arduino response: {response}")  # Debugging print
            if response == "Motion detected":
                print("Motion detected! Starting face recognition...")
                if real_time_recognition():
                    print("Access granted.")
                else:
                    print("Access denied.")
            elif response == "No motion detected":
                print("No motion detected.") 
            time.sleep(1)
    except KeyboardInterrupt:
        print("Program interrupted. Exiting...")
    finally:
        arduino.close()

# Start the main function
check_motion_and_recognize_face()


ImportError: cannot import name 'Serial' from 'serial' (c:\Users\rbvai\AppData\Local\Programs\Python\Python311\Lib\site-packages\serial\__init__.py)