In [2]:
import cv2
import time

In [30]:
def generate_dataset(Name):
    face_classifier = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
    
    def face_cropped(img):
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        faces = face_classifier.detectMultiScale(gray, 1.3, 5)
        
        if len(faces) == 0:
            return None
        for (x, y, w, h) in faces:
            cropped_face = img[y:y+h, x:x+w]
        return cropped_face
    
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("Error: Could not open video capture")
        return
    
    img_id = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            print("Failed to capture image")
            break
        
        cropped_face = face_cropped(frame)
        if cropped_face is not None:
            img_id += 1
            face = cv2.resize(cropped_face, (200, 200))
            face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)
            file_name_path = "C:/Vaibhav Data/Proffesional/Engineering/NHCE/Sem 6/Mini Project - III/Face_recog/data/"+ Name + str(img_id) + ".jpg"
            cv2.imwrite(file_name_path, face)
            cv2.putText(face, str(img_id), (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)
            
            cv2.imshow("Cropped_Face", face)
            if cv2.waitKey(1) == 13 or img_id == 50:
                break
        else:
            cv2.imshow("Camera Feed", frame)
            if cv2.waitKey(1) == 13:
                break
    
    cap.release()
    cv2.destroyAllWindows()
    print("Collecting samples is completed.")

generate_dataset("Vaibhav")
time.sleep(10)
generate_dataset("Sruthi")

In [4]:
import numpy as np

In [27]:
import os

def find_images(directory, extensions=None):
    """
    Finds all images in a given directory with specified extensions.
    
    Args:
        directory (str): Path to the directory to search for images.
        extensions (list): List of valid image file extensions (default: common formats).
    
    Returns:
        list: List of paths to image files.
    """
    if extensions is None:
        # Default to common image extensions
        extensions = ['.jpg', '.jpeg', '.png']
    
    # Normalize extensions to lowercase
    extensions = [ext.lower() for ext in extensions]
    
    # List to hold image paths
    image_files = []
    
    # Walk through the directory
    for root, _, files in os.walk(directory):
        for file in files:
            if os.path.splitext(file)[1].lower() in extensions:
                image_files.append(os.path.join(root, file))
    
    return image_files

# Example usage
directory_path = "indian_faces"  # Replace with your directory path
images = find_images(directory_path)

print("Found Images:")
count = 0
for image in images:
    count += 1
    print(count, image)



Found Images:
1 indian_faces\06298d548430d752925da79fdc2f8f32.jpg
2 indian_faces\1200px-Old_Indian_man2C_Bihar2C_India2C_2012.jpg
3 indian_faces\1670649912-3704.jpeg
4 indian_faces\2008-10-06_IMG_8607.jpg
5 indian_faces\2008-10-14_IMG_9489.jpg
6 indian_faces\2560px-Indian_male_face.jpg
7 indian_faces\2807.jpg
8 indian_faces\360_F_463221858_50KkvfxxovUaMNlilCmUxrOnTqSpzAlP.jpg
9 indian_faces\360_F_620730419_9cf73do9dxGaNJCztZPETHdB5bdrbW5D.jpg
10 indian_faces\5da8768c07eb3db7dbf5f394ab4444a6.jpg
11 indian_faces\847aa4ea94e646a239324307bc3b4236.jpg
12 indian_faces\91808573.jpg
13 indian_faces\a-face-young-handsome-indian-man-isolated-against-white-background-131186211.jpg
14 indian_faces\AF2bZyiAgReabunzr39lBthF2McS20v-ZJ1X9LClybZ5iILYIEnSs64-c-mo.jpg
15 indian_faces\asian-man-indian-origin-7252735.jpg
16 indian_faces\bc976b2596bbb9e5ca0e9a9ad9839be4.png
17 indian_faces\boy-happy-mood-asian-smiling-260nw-2374333277.jpg
18 indian_faces\c8b276ea169aecb66cd0b7e6ad114274.jpg
19 indian_faces\

In [28]:
import cv2
import os

def extract_faces(image_path, output_dir, count,resize_dim=(200, 200)):
    """
    Extracts faces from an image, converts them to grayscale, resizes them, 
    and saves them as 50x50 images.
    
    Args:
        image_path (str): Path to the input image.
        output_dir (str): Directory to save the extracted face images.
        resize_dim (tuple): Dimensions to resize the face images (default: (50, 50)).
    """
    # Load the image
    image = cv2.imread(image_path)
    if image is None:
        print(f"Error: Unable to load image {image_path}")
        return
    
    # Convert to grayscale for face detection
    gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    # Load pre-trained Haar Cascade for face detection
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    
    # Detect faces in the image
    faces = face_cascade.detectMultiScale(gray_image, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))
    
    if len(faces) == 0:
        print("No faces detected in the image.")
        return
    
    # Ensure the output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    # Process each detected face
    for i, (x, y, w, h) in enumerate(faces):
        # Extract the face region
        face = gray_image[y:y+h, x:x+w]
        
        # Resize to the desired dimensions
        resized_face = cv2.resize(face, resize_dim)
        
        # Save the resized grayscale face image
        output_path = os.path.join(output_dir, f"intruder_{count+i+1}.png")
        cv2.imwrite(output_path, resized_face)
        print(f"Saved face {i+1} to {output_path}")

directory_path = "indian_faces"  # Replace with your directory path
images = find_images(directory_path)

print("Found Images:")
for idx, image in enumerate(images):
    extract_faces(image, "data", count=idx+1)

Found Images:
Saved face 1 to data\intruder_2.png
Saved face 2 to data\intruder_3.png
Saved face 1 to data\intruder_3.png
Saved face 2 to data\intruder_4.png
Saved face 1 to data\intruder_4.png
Saved face 1 to data\intruder_5.png
Saved face 1 to data\intruder_6.png
Saved face 1 to data\intruder_7.png
Saved face 2 to data\intruder_8.png
Saved face 3 to data\intruder_9.png
Saved face 4 to data\intruder_10.png
Saved face 5 to data\intruder_11.png
Saved face 6 to data\intruder_12.png
Saved face 7 to data\intruder_13.png
Saved face 8 to data\intruder_14.png
Saved face 9 to data\intruder_15.png
Saved face 10 to data\intruder_16.png
Saved face 11 to data\intruder_17.png
Saved face 12 to data\intruder_18.png
Saved face 13 to data\intruder_19.png
Saved face 14 to data\intruder_20.png
Saved face 15 to data\intruder_21.png
Saved face 16 to data\intruder_22.png
Saved face 17 to data\intruder_23.png
Saved face 18 to data\intruder_24.png
Saved face 19 to data\intruder_25.png
Saved face 20 to data\in

In [31]:
# def my_label(image_name):
#     name = image_name.split('.')[0] 
    
#     if name=="Vaibhav":
#         return np.array([1,0])
#     elif name=="Sruthi":
#         return np.array([0,1])

def my_label(image_name):
    name = image_name.split('.')[0]  # Extract the part before the file extension
    
    if name.startswith("Vaibhav"):
        return np.array([1, 0, 0])
    elif name.startswith("Sruthi"):
        return np.array([0, 1, 0])
    else:
        return np.array([0, 0, 1])


In [32]:
import os
from random import shuffle
from tqdm import tqdm

In [43]:
def my_data():
    data = []
    for img in tqdm(os.listdir("data")):
        path=os.path.join("data",img)
        img_data = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img_data = cv2.resize(img_data, (50,50))
        data.append([np.array(img_data), my_label(img)])
        print(img)
    shuffle(data)  
    return data


In [44]:
data = my_data()
print(data)

100%|██████████| 203/203 [00:00<00:00, 1905.48it/s]

intruder_10.png
intruder_100.png
intruder_101.png
intruder_103.png
intruder_104.png
intruder_105.png
intruder_106.png
intruder_107.png
intruder_109.png
intruder_11.png
intruder_110.png
intruder_111.png
intruder_112.png
intruder_113.png
intruder_114.png
intruder_115.png
intruder_116.png
intruder_117.png
intruder_12.png
intruder_13.png
intruder_14.png
intruder_16.png
intruder_17.png
intruder_18.png
intruder_19.png
intruder_2.png
intruder_20.png
intruder_21.png
intruder_22.png
intruder_23.png
intruder_24.png
intruder_25.png
intruder_26.png
intruder_27.png
intruder_28.png
intruder_30.png
intruder_31.png
intruder_32.png
intruder_34.png
intruder_35.png
intruder_36.png
intruder_37.png
intruder_38.png
intruder_39.png
intruder_4.png
intruder_40.png
intruder_43.png
intruder_44.png
intruder_45.png
intruder_46.png
intruder_47.png
intruder_48.png
intruder_49.png
intruder_5.png
intruder_50.png
intruder_51.png
intruder_52.png
intruder_53.png
intruder_54.png
intruder_55.png
intruder_56.png
intruder_57

In [45]:
train = data[:150]  
test = data[150:]
X_train = np.array([i[0] for i in train]).reshape(-1,50,50,1)
print(X_train.shape)
y_train = np.array([i[1] for i in train])
X_test = np.array([i[0] for i in test]).reshape(-1,50,50,1)
print(X_test.shape)
y_test = np.array([i[1] for i in test])
print(y_train.shape)
len(y_train)

# One-hot encode the labels for categorical crossentropy
# y_train = tf.keras.utils.to_categorical(y_train, num_classes=2)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes=2)

print(y_train)
print(y_train.shape)

(150, 50, 50, 1)
(53, 50, 50, 1)
(150, 3)
[[0 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 

In [46]:
import tensorflow as tf
from tensorflow.keras import layers, models



# Define the model
model = models.Sequential()

# Add layers to the model
model.add(layers.Conv2D(32, (5, 5), activation='relu', input_shape=(50, 50, 1), padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(128, (5, 5), activation='relu', padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

model.add(layers.Conv2D(32, (5, 5), activation='relu', padding='same'))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))

# Flatten the output to feed into fully connected layers
model.add(layers.Flatten())
model.add(layers.Dense(1024, activation='relu'))
model.add(layers.Dropout(0.8))
model.add(layers.Dense(3, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# y_train = tf.keras.utils.to_categorical(y_train, num_classes=2)
# y_test = tf.keras.utils.to_categorical(y_test, num_classes=2)

# Fit the model

model.fit(X_train, y_train, epochs=12, validation_data=(X_test, y_test), batch_size=32)

# convnet = fully_connected(convnet, 1024, activation='relu')
# convnet = dropout(convnet, 0.8)
# convnet = fully_connected(convnet, 2, activation='softmax')
# convnet = regression(convnet, optimizer='adam', learning_rate = 0.001, loss='categorical_crossentropy')
# model = tflearn.DNN(convnet, tensorboard_verbose=1)
# model.fit(X_train, y_train, n_epoch=10, validation_set=(X_test, y_test), show_metric = True, run_id="FRS" )
# model.save('face_recognition_model.h5')
# print("Model saved as 'face_recognition_model.h5'")


Epoch 1/12


c:\Users\rbvai\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 87ms/step - accuracy: 0.3287 - loss: 3.1625 - val_accuracy: 0.5660 - val_loss: 0.9546
Epoch 2/12
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4264 - loss: 1.1098 - val_accuracy: 0.5660 - val_loss: 0.9555
Epoch 3/12
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5210 - loss: 0.9514 - val_accuracy: 0.5660 - val_loss: 0.8178
Epoch 4/12
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.4899 - loss: 0.8778 - val_accuracy: 0.6226 - val_loss: 0.5543
Epoch 5/12
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7028 - loss: 0.6421 - val_accuracy: 1.0000 - val_loss: 0.3868
Epoch 6/12
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8244 - loss: 0.4303 - val_accuracy: 0.9245 - val_loss: 0.2672
Epoch 7/12
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.9075 - loss: 0.2964 - val_accuracy: 0.9623 - val_loss: 0.1029
Epoch 8/12
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9231 - loss: 0.2063 - val_accuracy: 1.0000 - val_loss: 0.0337
Epoch 9/12


In [47]:
model.save("face_model.keras")

In [48]:
def data_for_visualization():
    Vdata = []
    for img in tqdm(os.listdir(r"C:\Vaibhav Data\Proffesional\Engineering\NHCE\Sem 6\Mini Project - III\Face_recog\Images for visualization")):
        path = os.path.join(r"C:\Vaibhav Data\Proffesional\Engineering\NHCE\Sem 6\Mini Project - III\Face_recog\Images for visualization", img)
        img_num = img.split('.')[0] 
        img_data = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        img_data = cv2.resize(img_data, (50,50))
        Vdata.append([np.array(img_data), img_num])
    shuffle(Vdata)
    return Vdata

In [49]:
import matplotlib.pyplot as plt   # installation command: pip install matplotlib
Vdata = data_for_visualization()
fig = plt.figure(figsize=(20,20))
for num, data in enumerate(Vdata[:20]):
    img_data = data[0]
    y = fig.add_subplot(5,5, num+1)
    image = img_data
    data = img_data.reshape(1,50,50,1)
    model_out = model.predict([data])[0]
     
    if np.argmax(model_out) == 0:
        my_label = 'Vaibhav'
    elif np.argmax(model_out) == 1:
        my_label = 'Sruthi'
    
         
    y.imshow(image, cmap='gray')
    
    # plt.title(my_label)
    plt.title(str(model_out[np.argmax(model_out)]*100))
    y.axes.get_xaxis().set_visible(False)
    y.axes.get_yaxis().set_visible(False)
plt.show()

0it [00:00, ?it/s]


<Figure size 2000x2000 with 0 Axes>

In [50]:
import cv2
import tensorflow as tf
import numpy as np

face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

model = tf.keras.models.load_model("face_model.keras")

def real_time_recognition():
    cap = cv2.VideoCapture(0)
    
    while True:
        ret, frame = cap.read()
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = face_classifier.detectMultiScale(gray, 1.3, 5) 
        # confidence = model.predict([data])[0]
    
        for (x, y, w, h) in faces:
            cropped_face = gray[y:y+h, x:x+w]
            cropped_face = cv2.resize(cropped_face, (50, 50)).reshape(1, 50, 50, 1)

            model_out = model.predict(cropped_face)[0]

            print(model_out)

            if np.argmax(model_out) == 0:
                label = 'Vaibhav'
            elif np.argmax(model_out) == 1:
                label = 'Sruthi'
            elif np.argmax(model_out) == 2:
                label = "Intruder"
            
            
            
            cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
            cv2.putText(frame, label, (x+4, y-6), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 0, 0), 2)
            cv2.putText(frame, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 0, 255), 2)
            cv2.putText(frame, str(model_out[np.argmax(model_out)]*100), (x, y-40), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 0), 2)
            
        cv2.imshow('Real-Time Face Recognition', frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

real_time_recognition()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
[0.00291387 0.9915611  0.00552497]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[0.00160048 0.99561393 0.0027856 ]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[0.00334619 0.9872168  0.00943702]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[9.0596819e-04 9.9660122e-01 2.4927685e-03]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[0.00272752 0.9902458  0.00702667]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[0.00105742 0.99417007 0.0047725 ]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[0.00110744 0.9943697  0.00452292]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[8.0280990e-04 9.9635339e-01 2.8437478e-03]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[0.00310306 0.9831508  0.01374619]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[9.6084934e-04 9.9628180e-01 2.7573446e-03]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[5.6491903e-04 9.9795204e-01 1.4831126e-03]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[7.4940099e-04 9.9779922e-01 1.4513062e-03]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[8.8812446e-04 9.9755681e-01 1.5549930e-0